spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/johnpauljayme
    username: johnpauljayme
    password:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083