spring:
  datasource:
    url: jdbc:postgresql://dpg-cordr4q0si5c739fm680-a.singapore-postgres.render.com/blog_jly6
    username: mayhm
    password: fERM5p8Rt35cFCHo0zAjHeljbFrbm7Kn
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
server:
  port: 8083

cloudfront:
  url: https://ddoo2mtjx0c7b.cloudfront.net