spring:
  datasource:
    url: jdbc:postgresql://dpg-coqf214f7o1s73ehhgng-a/blog_zy7h
#    url: jdbc:postgresql://dpg-coqf214f7o1s73ehhgng-a.singapore-postgres.render.com/blog_zy7h
    username: blog_zy7h_user
    password: EpTLw5sWxbtSeQwMxOcW0gy5gRHe3y9e
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
server:
  port: 8083

cloudfront:
  url: https://ddoo2mtjx0c7b.cloudfront.net