spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: johnpauljayme
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: 8083

cloudfront:
  url: https://ddoo2mtjx0c7b.cloudfront.net